FROM rust:1.65.0-bullseye

WORKDIR /src

# setup avr cross compiler
RUN apt update && apt install -y avr-libc gcc-avr pkg-config avrdude libudev-dev build-essential
RUN rustup toolchain install stable-aarch64-unknown-linux-gnu && rustup toolchain install nightly-2022-07-10-aarch64-unknown-linux-gnu --component rust-src
RUN cargo +stable install ravedude 
